"""adding closed timestamp to Service_ticket 

Revision ID: 0fbcd3f25ec2
Revises: c008be8cf1e0
Create Date: 2024-02-05 23:07:49.565276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fbcd3f25ec2'
down_revision = 'c008be8cf1e0'
branch_labels = None
depends_on = None


def upgrade():
    # Add the closed_timestamp column to the Service_ticket table
    op.add_column('service_ticket', sa.Column('closed_timestamp', sa.DateTime(timezone=True)))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_ticket', schema=None) as batch_op:
        batch_op.alter_column('service_ticket_nr',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
