"""Create SparePart, ServiceTicket, and ComputerListing models

Revision ID: 2c39a2e10ec8
Revises: ac6f281d7972
Create Date: 2024-01-31 20:17:03.719856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c39a2e10ec8'
down_revision = 'ac6f281d7972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_ticket', schema=None) as batch_op:
        batch_op.drop_column('purchase_timestamp')

    # ### end Alembic commands ###
