"""empty message

Revision ID: 31c02209951f
Revises: 7c551169673e
Create Date: 2024-01-19 08:17:18.878907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c02209951f'
down_revision = '7c551169673e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold_to_customer', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sale_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_listing', schema=None) as batch_op:
        batch_op.drop_column('sale_timestamp')
        batch_op.drop_column('sold_to_customer')

    # ### end Alembic commands ###
