"""adding closed timestamp to Service_ticket 

Revision ID: 58eec34a64fb
Revises: 0fbcd3f25ec2
Create Date: 2024-02-05 23:20:08.996974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58eec34a64fb'
down_revision = '0fbcd3f25ec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed_timestamp', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_ticket', schema=None) as batch_op:
        batch_op.drop_column('closed_timestamp')

    # ### end Alembic commands ###
