"""dodavanje vreme trajanja popravke 

Revision ID: 58f4998df96a
Revises: 9b744e5d8cfc
Create Date: 2024-02-07 00:46:36.098301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f4998df96a'
down_revision = '9b744e5d8cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complete_duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_ticket', schema=None) as batch_op:
        batch_op.drop_column('complete_duration')

    # ### end Alembic commands ###
