"""empty message

Revision ID: 7c551169673e
Revises: 
Create Date: 2024-01-19 07:53:11.192358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c551169673e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('imei', sa.BigInteger(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('capacity', sa.String(length=50), nullable=True),
    sa.Column('condition', sa.String(length=10), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('sales_price', sa.Float(), nullable=True),
    sa.Column('supplier_name', sa.String(length=100), nullable=True),
    sa.Column('supplier_id_card', sa.String(length=50), nullable=True),
    sa.Column('supplier_mobile', sa.String(length=15), nullable=True),
    sa.Column('purchase_timestamp', sa.DateTime(), nullable=True),
    sa.Column('sold', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone_listing')
    # ### end Alembic commands ###
