"""empty message

Revision ID: 9132c3473ff4
Revises: 8652109a3457
Create Date: 2024-01-22 02:40:36.747619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9132c3473ff4'
down_revision = '8652109a3457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_listing', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
