"""Add turnover_time column

Revision ID: 98bde5e597f2
Revises: 31c02209951f
Create Date: 2024-01-20 00:37:23.082236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98bde5e597f2'
down_revision = '31c02209951f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turnover_time', sa.Interval(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_listing', schema=None) as batch_op:
        batch_op.drop_column('turnover_time')

    # ### end Alembic commands ###
