"""empty message

Revision ID: c85e36952b0c
Revises: 9132c3473ff4
Create Date: 2024-01-22 02:50:53.272671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85e36952b0c'
down_revision = '9132c3473ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_listing', schema=None) as batch_op:
        batch_op.drop_column('sold_to_customer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold_to_customer', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
