"""Create SparePart, ServiceTicket, and ComputerListing models

Revision ID: cc311c299bcb
Revises: ac590c126d40
Create Date: 2024-01-31 19:27:16.959817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc311c299bcb'
down_revision = 'ac590c126d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('computer_listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('cpu_brand', sa.String(length=100), nullable=True),
    sa.Column('cpu_model', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.String(length=50), nullable=True),
    sa.Column('hdd', sa.String(length=100), nullable=True),
    sa.Column('hdd_type', sa.String(length=50), nullable=True),
    sa.Column('graphics_card_model', sa.String(length=100), nullable=True),
    sa.Column('screen_size', sa.String(length=50), nullable=True),
    sa.Column('screen_type', sa.String(length=50), nullable=True),
    sa.Column('condition', sa.String(length=10), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('sales_price', sa.Float(), nullable=True),
    sa.Column('supplier_name', sa.String(length=100), nullable=True),
    sa.Column('supplier_id_card', sa.String(length=50), nullable=True),
    sa.Column('supplier_mobile', sa.String(length=15), nullable=True),
    sa.Column('purchase_timestamp', sa.DateTime(), nullable=True),
    sa.Column('sold', sa.Boolean(), nullable=True),
    sa.Column('sale_timestamp', sa.DateTime(), nullable=True),
    sa.Column('turnover_time', sa.Interval(), nullable=True),
    sa.Column('collected', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_ticket_nr', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_contact', sa.String(length=20), nullable=True),
    sa.Column('customer_mail', sa.String(length=100), nullable=True),
    sa.Column('customer_company_name', sa.String(length=100), nullable=True),
    sa.Column('customer_pib', sa.String(length=15), nullable=True),
    sa.Column('service_section', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('imei', sa.BigInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('ticket_status', sa.String(length=20), nullable=True),
    sa.Column('sales_price', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('assigned_technician', sa.String(length=100), nullable=True),
    sa.Column('resolution_details', sa.Text(), nullable=True),
    sa.Column('parent_ticket_id', sa.Integer(), nullable=True),
    sa.Column('attachments', sa.String(length=200), nullable=True),
    sa.Column('billing_status', sa.String(length=20), nullable=True),
    sa.Column('invoice_number', sa.String(length=20), nullable=True),
    sa.Column('service_location', sa.String(length=100), nullable=True),
    sa.Column('notification_preference', sa.String(length=20), nullable=True),
    sa.Column('ticket_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_ticket_id'], ['service_ticket.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_ticket_nr')
    )
    op.create_table('spare_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_section', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('part_name', sa.String(length=100), nullable=True),
    sa.Column('part_number', sa.String(length=50), nullable=True),
    sa.Column('part_category', sa.String(length=50), nullable=True),
    sa.Column('picture', sa.String(length=200), nullable=True),
    sa.Column('original_part', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('quantity_in_stock', sa.Integer(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('sales_price', sa.Float(), nullable=True),
    sa.Column('warehouse_location', sa.String(length=100), nullable=True),
    sa.Column('purchase_timestamp', sa.DateTime(), nullable=True),
    sa.Column('collected', sa.Boolean(), nullable=True),
    sa.Column('inventory_code', sa.String(length=50), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('imei', sa.BigInteger(), nullable=True),
    sa.Column('condition', sa.String(length=10), nullable=True),
    sa.Column('sold', sa.Boolean(), nullable=True),
    sa.Column('sale_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('inventory_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spare_part')
    op.drop_table('service_ticket')
    op.drop_table('computer_listing')
    # ### end Alembic commands ###
