"""Remove deleted models

Revision ID: d4332618c046
Revises: 93db02a883dc
Create Date: 2024-01-21 23:39:35.302664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4332618c046'
down_revision = '93db02a883dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_listing', schema=None) as batch_op:
        batch_op.drop_column('total_sales_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_sales_amount', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
