"""adding collected_timestamp, owner_collect, and owner_collect_timestamp fields to your ServiceTicket 

Revision ID: ebe52ea8b39b
Revises: 58eec34a64fb
Create Date: 2024-02-06 22:19:35.864041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe52ea8b39b'
down_revision = '58eec34a64fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collected_timestamp', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('owner_collect', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('owner_collect_timestamp', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_ticket', schema=None) as batch_op:
        batch_op.drop_column('owner_collect_timestamp')
        batch_op.drop_column('owner_collect')
        batch_op.drop_column('collected_timestamp')

    # ### end Alembic commands ###
